################################################################################
# Git Backup Automation Package
# - Runs git_backup.py (exports dashboards + git commit/push)
# - Exposes "last backup" and "history" sensors for UI
################################################################################

shell_command:
  git_backup: "python3 /config/git_backup.py"

script:
  git_backup:
    alias: "GitHub Backup"
    icon: mdi:github
    mode: single
    sequence:
      - service: shell_command.git_backup

sensor:
  # Single timestamp of last backup
  - platform: file
    name: "Git Last Backup File"
    file_path: /config/.git_last_backup
    scan_interval: 60

  # History log (one line per backup)
  - platform: file
    name: "Git Backup History"
    file_path: /config/.git_backup_history
    scan_interval: 60

template:
  - sensor:
      - name: "Git Last Backup"
        unique_id: git_last_backup
        icon: mdi:clock-check
        state: >
          {% set raw = states('sensor.git_last_backup_file') %}
          {% if raw not in ['unknown', 'unavailable', ''] %}
            {{ as_timestamp(raw) | timestamp_custom('%b %d, %H:%M', true) }}
          {% else %}
            Never
          {% endif %}