# =============================================================================
# CUARTO MARIA - PRESENCE-BASED AUTOMATION PACKAGE
# =============================================================================
# Features:
#   - Bayesian presence detection (BLE + motion)
#   - Light automation with lux threshold, time window, and manual override
#   - AC auto-off when room empty + temperature regulation
#   - TV auto-off when room empty
# =============================================================================
# NOTE: All automations are DISABLED by default. Enable after configuration.
# =============================================================================

input_text:
  cuarto_maria_tv_entity:
    name: "Cuarto Maria - TV Entity"
    initial: "none"
    icon: mdi:television

input_select:
  cuarto_maria_light_selector:
    name: "Cuarto Maria - Light to Control"
    options:
      - light.cuarto_maria
    initial: light.cuarto_maria
    icon: mdi:lightbulb

input_boolean:
  cuarto_maria_light_automation_enabled:
    name: "Cuarto Maria - Light Automation Enabled"
    icon: mdi:lightbulb-auto
    initial: off

  cuarto_maria_light_program_cancelled:
    name: "Cuarto Maria - Light Program Cancelled"
    icon: mdi:cancel
    initial: off

  cuarto_maria_ac_automation_enabled:
    name: "Cuarto Maria - AC Automation Enabled"
    icon: mdi:air-conditioner
    initial: off

  cuarto_maria_ac_regulation_enabled:
    name: "Cuarto Maria - AC Temperature Regulation Enabled"
    icon: mdi:thermostat-auto
    initial: off

  cuarto_maria_tv_automation_enabled:
    name: "Cuarto Maria - TV Auto-Off Enabled"
    icon: mdi:television-off
    initial: off

input_number:
  cuarto_maria_lux_threshold:
    name: "Cuarto Maria - Lux Threshold"
    min: 0
    max: 100
    step: 5
    unit_of_measurement: "lx"
    icon: mdi:brightness-6
    initial: 50

  cuarto_maria_light_off_delay:
    name: "Cuarto Maria - Light Off Delay"
    min: 1
    max: 30
    step: 1
    unit_of_measurement: "min"
    icon: mdi:timer-outline
    initial: 5

  cuarto_maria_presence_threshold:
    name: "Cuarto Maria - Presence Probability Threshold"
    min: 0.3
    max: 0.9
    step: 0.05
    icon: mdi:account-question
    initial: 0.5

  cuarto_maria_ac_off_delay:
    name: "Cuarto Maria - AC Off Delay"
    min: 1
    max: 60
    step: 1
    unit_of_measurement: "min"
    icon: mdi:timer-outline
    initial: 5

  cuarto_maria_ac_target_temp:
    name: "Cuarto Maria - Target Temperature"
    min: 16
    max: 28
    step: 0.5
    unit_of_measurement: "°C"
    icon: mdi:thermometer
    initial: 22

  cuarto_maria_ac_min_setpoint:
    name: "Cuarto Maria - AC Minimum Setpoint"
    min: 16
    max: 24
    step: 1
    unit_of_measurement: "°C"
    icon: mdi:thermometer-chevron-down
    initial: 18

  cuarto_maria_ac_max_setpoint:
    name: "Cuarto Maria - AC Maximum Setpoint"
    min: 20
    max: 30
    step: 1
    unit_of_measurement: "°C"
    icon: mdi:thermometer-chevron-up
    initial: 26

  cuarto_maria_ac_external_temp_reference:
    name: "Cuarto Maria - Outside Neutral Temp"
    min: 20
    max: 30
    step: 1
    unit_of_measurement: "°C"
    icon: mdi:thermometer-alert
    initial: 23

  cuarto_maria_ac_external_correction_factor:
    name: "Cuarto Maria - External Correction Factor"
    min: 0
    max: 1
    step: 0.1
    icon: mdi:tune
    initial: 0.5

  cuarto_maria_ac_regulation_interval:
    name: "Cuarto Maria - AC Regulation Interval"
    min: 5
    max: 60
    step: 5
    unit_of_measurement: "min"
    icon: mdi:timer-sync-outline
    initial: 15

  cuarto_maria_temp_calibration_offset:
    name: "Cuarto Maria - Temperature Calibration Offset"
    min: -4
    max: 4
    step: 0.5
    unit_of_measurement: "°C"
    icon: mdi:thermometer-plus
    initial: 0

  cuarto_maria_tv_off_delay:
    name: "Cuarto Maria - TV Off Delay"
    min: 1
    max: 60
    step: 1
    unit_of_measurement: "min"
    icon: mdi:timer-outline
    initial: 10

input_datetime:
  cuarto_maria_light_start_time:
    name: "Cuarto Maria - Light Program Start"
    has_date: false
    has_time: true
    initial: "17:00:00"
    icon: mdi:weather-sunset-up

  cuarto_maria_light_end_time:
    name: "Cuarto Maria - Light Program End"
    has_date: false
    has_time: true
    initial: "23:00:00"
    icon: mdi:weather-sunset-down

  cuarto_maria_ac_autooff_start:
    name: "Cuarto Maria - AC Auto-Off Start"
    has_date: false
    has_time: true
    initial: "08:00:00"
    icon: mdi:clock-start

  cuarto_maria_ac_autooff_end:
    name: "Cuarto Maria - AC Auto-Off End"
    has_date: false
    has_time: true
    initial: "23:00:00"
    icon: mdi:clock-end

  cuarto_maria_ac_resume_start:
    name: "Cuarto Maria - AC Auto-Resume Start"
    has_date: false
    has_time: true
    initial: "00:00:00"
    icon: mdi:clock-start

  cuarto_maria_ac_resume_end:
    name: "Cuarto Maria - AC Auto-Resume End"
    has_date: false
    has_time: true
    initial: "08:00:00"
    icon: mdi:clock-end

timer:
  cuarto_maria_ac_regulation:
    name: "Cuarto Maria - AC Regulation Timer"
    restore: true

template:
  - sensor:
      - name: "Cuarto Maria Average Lux"
        unique_id: cuarto_maria_average_lux
        unit_of_measurement: "lx"
        state_class: measurement
        device_class: illuminance
        state: >
          {{ states('sensor.cuarto_maria_illuminance') | float(0) }}

      - name: "Cuarto Maria Current Temperature"
        unique_id: cuarto_maria_current_temperature
        unit_of_measurement: "°C"
        state_class: measurement
        device_class: temperature
        state: >
          {% set ac_temp = state_attr('climate.aire_maria', 'current_temperature') | float(20) %}
          {% set offset = states('input_number.cuarto_maria_temp_calibration_offset') | float(0) %}
          {{ (ac_temp + offset) | round(1) }}

      - name: "Cuarto Maria AC Calculated Setpoint"
        unique_id: cuarto_maria_ac_calculated_setpoint
        unit_of_measurement: "°C"
        state: >
          {% set target = states('input_number.cuarto_maria_ac_target_temp') | float(22) %}
          {% set current = states('sensor.cuarto_maria_current_temperature') | float(22) %}
          {% set external = states('sensor.hp2564bu_pro_v1_9_9_feels_like_temperature') | float(25) %}
          {% set min_sp = states('input_number.cuarto_maria_ac_min_setpoint') | float(18) %}
          {% set max_sp = states('input_number.cuarto_maria_ac_max_setpoint') | float(26) %}
          {% set ext_ref = states('input_number.cuarto_maria_ac_external_temp_reference') | float(25) %}
          {% set ext_factor = states('input_number.cuarto_maria_ac_external_correction_factor') | float(0.5) %}
          {% set error = current - target %}
          {% set base_adjustment = error * 1.5 %}
          {% set external_diff = external - ext_ref %}
          {% set external_correction = (external_diff / 5) * ext_factor %}
          {% set external_correction = [[external_correction, -2] | max, 2] | min %}
          {% set total_adjustment = base_adjustment + external_correction %}
          {% set new_setpoint = target - total_adjustment %}
          {{ [[new_setpoint, min_sp] | max, max_sp] | min | round(0) }}

  - binary_sensor:
      - name: "Cuarto Maria Light Program Active"
        unique_id: cuarto_maria_light_program_active
        state: >
          {% set start = states('input_datetime.cuarto_maria_light_start_time') %}
          {% set end = states('input_datetime.cuarto_maria_light_end_time') %}
          {% set now_time = now().strftime('%H:%M:%S') %}
          {% if end < start %}
            {{ now_time >= start or now_time < end }}
          {% else %}
            {{ start <= now_time < end }}
          {% endif %}

      - name: "Cuarto Maria Lux Below Threshold"
        unique_id: cuarto_maria_lux_below_threshold
        state: >
          {{ states('sensor.cuarto_maria_average_lux') | float(0) < 
             states('input_number.cuarto_maria_lux_threshold') | float(50) }}

      - name: "Cuarto Maria Light Trigger Allowed"
        unique_id: cuarto_maria_light_trigger_allowed
        state: >
          {{ is_state('input_boolean.cuarto_maria_light_automation_enabled', 'on') and
             is_state('binary_sensor.cuarto_maria_light_program_active', 'on') and
             is_state('binary_sensor.cuarto_maria_lux_below_threshold', 'on') and
             is_state('input_boolean.cuarto_maria_light_program_cancelled', 'off') }}

      - name: "Cuarto Maria Occupied"
        unique_id: cuarto_maria_occupied
        device_class: occupancy
        state: >
          {{ state_attr('binary_sensor.cuarto_maria_presence_probability', 'probability') | float(0) >= 
             states('input_number.cuarto_maria_presence_threshold') | float(0.5) }}

      - name: "Cuarto Maria AC AutoOff Window"
        unique_id: cuarto_maria_ac_autooff_window
        state: >
          {% set start = states('input_datetime.cuarto_maria_ac_autooff_start') %}
          {% set end = states('input_datetime.cuarto_maria_ac_autooff_end') %}
          {% set now_time = now().strftime('%H:%M:%S') %}
          {% if end < start %}
            {{ now_time >= start or now_time < end }}
          {% else %}
            {{ start <= now_time < end }}
          {% endif %}

      - name: "Cuarto Maria AC Resume Window"
        unique_id: cuarto_maria_ac_resume_window
        state: >
          {% set start = states('input_datetime.cuarto_maria_ac_resume_start') %}
          {% set end = states('input_datetime.cuarto_maria_ac_resume_end') %}
          {% set now_time = now().strftime('%H:%M:%S') %}
          {% if end < start %}
            {{ now_time >= start or now_time < end }}
          {% else %}
            {{ start <= now_time < end }}
          {% endif %}

binary_sensor:
  - platform: bayesian
    name: "Cuarto Maria Presence Probability"
    unique_id: cuarto_maria_presence_probability
    probability_threshold: 0.5
    prior: 0.25
    observations:
      # BLE: Any phone/tablet in this area
      - platform: template
        value_template: >
          { states('sensor.iphone_manuel_ble_area') == 'Cuarto Maria' or
             states('sensor.iphone_evelyn_area') == 'Cuarto Maria' or
             states('sensor.iphone_andres_ble_area') == 'Cuarto Maria' or
             states('sensor.ipad_manuel_area') == 'Cuarto Maria' or
             states('sensor.ipad_evelyn_area') == 'Cuarto Maria' }
        prob_given_true: 0.95
        prob_given_false: 0.10

      # Motion sensors
      - platform: template
        value_template: >
          {{ is_state('binary_sensor.cuarto_maria_motion', 'on') }}
        prob_given_true: 0.90
        prob_given_false: 0.25

      # Magic Areas (if available)
      - platform: state
        entity_id: binary_sensor.magic_areas_presence_tracking_cuarto_maria_area_state
        to_state: "on"
        prob_given_true: 0.80
        prob_given_false: 0.25

      # Light state
      - platform: template
        value_template: "{{ states(states('input_select.cuarto_maria_light_selector')) == 'on' }}"
        prob_given_true: 0.60
        prob_given_false: 0.35

      # AC state
      - platform: state
        entity_id: climate.aire_maria
        to_state: "cool"
        prob_given_true: 0.55
        prob_given_false: 0.35

automation:
  # Populate light selector on startup
  - id: cuarto_maria_populate_light_selector
    alias: "Cuarto Maria - Populate Light Selector"
    mode: single
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: input_select.set_options
        target:
          entity_id: input_select.cuarto_maria_light_selector
        data:
          options: >
            {{ states.light | map(attribute='entity_id') | list | sort }}

  # Light ON when presence detected
  - id: cuarto_maria_lights_on_presence
    alias: "Cuarto Maria - Lights On (Presence)"
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.cuarto_maria_occupied
        to: "on"
      - platform: state
        entity_id:
          - binary_sensor.cuarto_maria_motion
        to: "on"
    condition:
      - condition: state
        entity_id: binary_sensor.cuarto_maria_light_trigger_allowed
        state: "on"
      - condition: template
        value_template: "{{ states(states('input_select.cuarto_maria_light_selector')) == 'off' }}"
    action:
      - service: light.turn_on
        target:
          entity_id: "{{ states('input_select.cuarto_maria_light_selector') }}"

  # Light OFF when room empty
  - id: cuarto_maria_lights_off_empty
    alias: "Cuarto Maria - Lights Off (Empty)"
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.cuarto_maria_occupied
        to: "off"
        for:
          minutes: "{{ states('input_number.cuarto_maria_light_off_delay') | int(5) }}"
    condition:
      - condition: state
        entity_id: input_boolean.cuarto_maria_light_automation_enabled
        state: "on"
      - condition: template
        value_template: "{{ states(states('input_select.cuarto_maria_light_selector')) == 'on' }}"
    action:
      - service: light.turn_off
        target:
          entity_id: "{{ states('input_select.cuarto_maria_light_selector') }}"

  # Reset light program cancelled flag
  - id: cuarto_maria_reset_light_program
    alias: "Cuarto Maria - Reset Light Program"
    mode: single
    trigger:
      - platform: time
        at: input_datetime.cuarto_maria_light_start_time
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.cuarto_maria_light_program_cancelled

  # AC OFF when room empty
  - id: cuarto_maria_ac_off_empty
    alias: "Cuarto Maria - AC Off (Empty)"
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.cuarto_maria_occupied
        to: "off"
        for:
          minutes: "{{ states('input_number.cuarto_maria_ac_off_delay') | int(5) }}"
    condition:
      - condition: state
        entity_id: input_boolean.cuarto_maria_ac_automation_enabled
        state: "on"
      - condition: state
        entity_id: binary_sensor.cuarto_maria_ac_autooff_window
        state: "on"
      - condition: not
        conditions:
          - condition: state
            entity_id: climate.aire_maria
            state: "off"
    action:
      - service: climate.turn_off
        target:
          entity_id: climate.aire_maria

  # AC Temperature Regulation
  - id: cuarto_maria_ac_regulate_temperature
    alias: "Cuarto Maria - AC Temperature Regulation"
    mode: single
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.cuarto_maria_ac_regulation
    condition:
      - condition: state
        entity_id: input_boolean.cuarto_maria_ac_regulation_enabled
        state: "on"
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{ (states('input_number.cuarto_maria_ac_target_temp') | float(22) - 
                      states('sensor.cuarto_maria_current_temperature') | float(22)) > 2 }}
              - condition: not
                conditions:
                  - condition: state
                    entity_id: climate.aire_maria
                    state: "off"
            sequence:
              - service: climate.turn_off
                target:
                  entity_id: climate.aire_maria
          - conditions:
              - condition: state
                entity_id: climate.aire_maria
                state: "off"
              - condition: state
                entity_id: binary_sensor.cuarto_maria_ac_resume_window
                state: "on"
              - condition: template
                value_template: >
                  {{ (states('input_number.cuarto_maria_ac_target_temp') | float(22) - 
                      states('sensor.cuarto_maria_current_temperature') | float(22)) <= 2 }}
            sequence:
              - service: climate.turn_on
                target:
                  entity_id: climate.aire_maria
              - delay:
                  seconds: 5
              - service: climate.set_temperature
                target:
                  entity_id: climate.aire_maria
                data:
                  temperature: "{{ states('sensor.cuarto_maria_ac_calculated_setpoint') | float(22) }}"
          - conditions:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: climate.aire_maria
                    state: "off"
            sequence:
              - service: climate.set_temperature
                target:
                  entity_id: climate.aire_maria
                data:
                  temperature: "{{ states('sensor.cuarto_maria_ac_calculated_setpoint') | float(22) }}"
      - service: timer.start
        target:
          entity_id: timer.cuarto_maria_ac_regulation
        data:
          duration:
            minutes: "{{ states('input_number.cuarto_maria_ac_regulation_interval') | int(15) }}"

  # Start AC regulation timer
  - id: cuarto_maria_ac_start_regulation_timer
    alias: "Cuarto Maria - Start AC Regulation Timer"
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.cuarto_maria_ac_regulation_enabled
        to: "on"
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: input_boolean.cuarto_maria_ac_regulation_enabled
        state: "on"
    action:
      - service: timer.start
        target:
          entity_id: timer.cuarto_maria_ac_regulation
        data:
          duration:
            minutes: "{{ states('input_number.cuarto_maria_ac_regulation_interval') | int(15) }}"

  # Stop AC regulation timer
  - id: cuarto_maria_ac_stop_regulation_timer
    alias: "Cuarto Maria - Stop AC Regulation Timer"
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.cuarto_maria_ac_regulation_enabled
        to: "off"
    action:
      - service: timer.cancel
        target:
          entity_id: timer.cuarto_maria_ac_regulation

  # Regulate on AC start
  - id: cuarto_maria_ac_regulate_on_start
    alias: "Cuarto Maria - AC Regulate On Start"
    mode: single
    trigger:
      - platform: state
        entity_id: climate.aire_maria
        from: "off"
    condition:
      - condition: state
        entity_id: input_boolean.cuarto_maria_ac_regulation_enabled
        state: "on"
    action:
      - delay:
          seconds: 5
      - service: climate.set_temperature
        target:
          entity_id: climate.aire_maria
        data:
          temperature: "{{ states('sensor.cuarto_maria_ac_calculated_setpoint') | float(22) }}"

  # TV OFF when room empty
  - id: cuarto_maria_tv_off_empty
    alias: "Cuarto Maria - TV Off (Empty)"
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.cuarto_maria_occupied
        to: "off"
        for:
          minutes: "{{ states('input_number.cuarto_maria_tv_off_delay') | int(10) }}"
    condition:
      - condition: state
        entity_id: input_boolean.cuarto_maria_tv_automation_enabled
        state: "on"
      - condition: template
        value_template: "{{ states('input_text.cuarto_maria_tv_entity') != 'none' }}"
    action:
      - service: media_player.turn_off
        target:
          entity_id: "{{ states('input_text.cuarto_maria_tv_entity') }}"

