# /config/packages/systems_down/tuya.yaml
# Features:
# - Configurable debounce via slider (0-30 minutes)
# - Repeat notification every X hours (0 = disabled)
# - Alert tracking to prevent false recovery notifications
# - Only notifies if device still down after debounce period

input_boolean:
  alert_tuya_enabled:
    name: Tuya Alert
    icon: mdi:power-plug-outline

  # Alert tracking - only send recovery if DOWN was sent
  tuya_alerted:
    name: Tuya Alerted
    icon: mdi:alert-circle

input_number:
  tuya_debounce_minutes:
    name: Tuya Debounce
    icon: mdi:timer-sand
    min: 0
    max: 30
    step: 1
    unit_of_measurement: "min"
    initial: 5

  tuya_repeat_hours:
    name: Tuya Repeat
    icon: mdi:repeat
    min: 0
    max: 24
    step: 1
    unit_of_measurement: "hrs"
    initial: 0

# Store last alert time for repeat logic
input_datetime:
  tuya_last_alert:
    name: Tuya Last Alert
    has_date: true
    has_time: true

# Store which devices are currently down
input_text:
  tuya_devices_down:
    name: Tuya Devices Down
    max: 255
    initial: ""

script:
  test_tuya_notification:
    alias: Test Tuya Notification
    mode: single
    sequence:
      - action: script.whatsapp_info
        data:
          message: |
            🔴 🔌 *Test Device Down*
            *Time:* {{ now().strftime('%H:%M') }}
            *Date:* {{ now().strftime('%B %d, %Y') }}

automation:
  # ============ TUYA - FAILURE ============
  - id: 'tuya_alert_failure'
    alias: 'Tuya Alert - Failure'
    trigger:
      - platform: event
        event_type: state_changed
    condition:
      - condition: state
        entity_id: input_boolean.alert_tuya_enabled
        state: 'on'
      - condition: template
        value_template: >
          {{ trigger.event.data.entity_id in [
            'sensor.breaker_calentadores_status',
            'sensor.cortina_musica_derecha_status',
            'sensor.cortina_musica_izquierda_status',
            'sensor.luces_arbol_derecho_status',
            'sensor.luces_arbol_izquierdo_status',
            'sensor.toma_doble_jardin_status',
            'sensor.tv_mount_status',
            'sensor.ventilador_solario_status'
          ] }}
      - condition: template
        value_template: "{{ trigger.event.data.old_state.state | lower in ['up','online','ok','ready','healthy','on','true','1'] }}"
      - condition: template
        value_template: "{{ trigger.event.data.new_state.state | lower not in ['up','online','ok','ready','healthy','on','true','1'] }}"
    action:
      # Store which entity triggered (for checking after delay)
      - variables:
          failed_entity: "{{ trigger.event.data.entity_id }}"
          failed_name: "{{ state_attr(trigger.event.data.entity_id, 'friendly_name') | replace(' Status', '') }}"
          debounce_mins: "{{ states('input_number.tuya_debounce_minutes') | int(5) }}"
      
      # Wait for debounce period (skip if 0)
      - if:
          - condition: template
            value_template: "{{ debounce_mins > 0 }}"
        then:
          - delay:
              minutes: "{{ debounce_mins }}"
          
          # Check if STILL down after debounce
          - condition: template
            value_template: "{{ states(failed_entity) | lower not in ['up','online','ok','ready','healthy','on','true','1'] }}"
      
      # Add to devices down list (with duplicate check)
      - action: input_text.set_value
        target:
          entity_id: input_text.tuya_devices_down
        data:
          value: >
            {% set current = states('input_text.tuya_devices_down') %}
            {% set current_list = current.split(',') | map('trim') | reject('eq', '') | list %}
            {% if failed_name not in current_list %}
              {% set new_list = current_list + [failed_name] %}
              {{ new_list | join(',') | truncate(255, True, '') }}
            {% else %}
              {{ current }}
            {% endif %}
      
      # Send notification
      - action: script.whatsapp_info
        data:
          message: |
            🔴 🔌 *{{ failed_name }} Down*
            *Time:* {{ now().strftime('%H:%M') }}
            *Date:* {{ now().strftime('%B %d, %Y') }}
      
      # Record alert time
      - action: input_datetime.set_datetime
        target:
          entity_id: input_datetime.tuya_last_alert
        data:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
      
      # Mark as alerted
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.tuya_alerted

  # ============ TUYA - RECOVERY ============
  - id: 'tuya_alert_recovery'
    alias: 'Tuya Alert - Recovery'
    trigger:
      - platform: event
        event_type: state_changed
    condition:
      - condition: state
        entity_id: input_boolean.alert_tuya_enabled
        state: 'on'
      - condition: template
        value_template: >
          {{ trigger.event.data.entity_id in [
            'sensor.breaker_calentadores_status',
            'sensor.cortina_musica_derecha_status',
            'sensor.cortina_musica_izquierda_status',
            'sensor.luces_arbol_derecho_status',
            'sensor.luces_arbol_izquierdo_status',
            'sensor.toma_doble_jardin_status',
            'sensor.tv_mount_status',
            'sensor.ventilador_solario_status'
          ] }}
      - condition: template
        value_template: "{{ trigger.event.data.old_state.state | lower not in ['up','online','ok','ready','healthy','on','true','1'] }}"
      - condition: template
        value_template: "{{ trigger.event.data.new_state.state | lower in ['up','online','ok','ready','healthy','on','true','1'] }}"
      # Only send recovery if DOWN was sent
      - condition: state
        entity_id: input_boolean.tuya_alerted
        state: 'on'
      # Only send recovery if THIS device was reported down
      - condition: template
        value_template: >
          {% set recovered_name = state_attr(trigger.event.data.entity_id, 'friendly_name') | replace(' Status', '') %}
          {{ recovered_name in states('input_text.tuya_devices_down').split(',') | map('trim') | list }}
    action:
      - variables:
          recovered_name: "{{ state_attr(trigger.event.data.entity_id, 'friendly_name') | replace(' Status', '') }}"
      
      # Remove from devices down list
      - action: input_text.set_value
        target:
          entity_id: input_text.tuya_devices_down
        data:
          value: >
            {% set current = states('input_text.tuya_devices_down') %}
            {% set devices = current.split(',') | map('trim') | reject('eq', recovered_name) | reject('eq', '') | list %}
            {{ devices | join(',') }}
      
      - action: script.whatsapp_info
        data:
          message: |
            🟢 🔌 *{{ recovered_name }} Recovered*
            *Time:* {{ now().strftime('%H:%M') }}
            *Date:* {{ now().strftime('%B %d, %Y') }}
      
      # Clear alerted state only if no more devices down
      - if:
          - condition: template
            value_template: "{{ states('input_text.tuya_devices_down') | trim == '' }}"
        then:
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.tuya_alerted

  # ============ TUYA - REPEAT REMINDER ============
  - id: 'tuya_alert_repeat'
    alias: 'Tuya Alert - Repeat Reminder'
    trigger:
      - platform: time_pattern
        minutes: "/15"
    condition:
      - condition: state
        entity_id: input_boolean.alert_tuya_enabled
        state: 'on'
      - condition: state
        entity_id: input_boolean.tuya_alerted
        state: 'on'
      # Repeat hours must be > 0
      - condition: template
        value_template: "{{ states('input_number.tuya_repeat_hours') | int(0) > 0 }}"
      # Must have devices down
      - condition: template
        value_template: "{{ states('input_text.tuya_devices_down') | trim != '' }}"
      # Check if enough time has passed since last alert
      - condition: template
        value_template: >
          {% set last = states('input_datetime.tuya_last_alert') %}
          {% set repeat_hrs = states('input_number.tuya_repeat_hours') | int(0) %}
          {% if last and last not in ['unknown', 'unavailable'] %}
            {{ (now() - last | as_datetime).total_seconds() >= (repeat_hrs * 3600) }}
          {% else %}
            false
          {% endif %}
    action:
      - action: script.whatsapp_info
        data:
          message: |
            🔴 🔌 *Tuya Devices Still Down*
            *Devices:* {{ states('input_text.tuya_devices_down') }}
            *Time:* {{ now().strftime('%H:%M') }}
            *Date:* {{ now().strftime('%B %d, %Y') }}
      
      # Update last alert time
      - action: input_datetime.set_datetime
        target:
          entity_id: input_datetime.tuya_last_alert
        data:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
